"""
Complete acronym dictionary from NASA Systems Engineering Handbook (SP-2016-6105 Rev2)
Appendix A — all acronyms as listed in the official document.
"""

ACRONYM_MAP = {
    "AADL": "Architecture Analysis and Design Language",
    "AD2": "Advancement Degree of Difficulty Assessment",
    "AIAA": "American Institute of Aeronautics and Astronautics",
    "AO": "Announcement of Opportunity",
    "AS9100": "Aerospace Quality Management Standard",
    "ASME": "American Society of Mechanical Engineers",
    "ASQ": "American Society for Quality",
    "CAIB": "Columbia Accident Investigation Board",
    "CCB": "Configuration Control Board",
    "CDR": "Critical Design Review",
    "CE": "Concurrent Engineering or Chief Engineer",
    "CEQ": "Council on Environmental Quality",
    "CERR": "Critical Event Readiness Review",
    "CHSIP": "Commercial Human Systems Integration Processes",
    "CI": "Configuration Item",
    "CM": "Configuration Management",
    "CMO": "Configuration Management Organization",
    "ConOps": "Concept of Operations",
    "CONOPS": "Concept of Operations",
    "COSPAR": "Committee on Space Research",
    "COTS": "Commercial Off-The-Shelf",
    "CPI": "Critical Program Information",
    "CR": "Change Request",
    "CRM": "Continuous Risk Management",
    "CSA": "Configuration Status Accounting",
    "D&C": "Design and Construction",
    "DDT&E": "Design, Development, Test, and Evaluation",
    "DM": "Data Management",
    "DOD": "Department of Defense",
    "DODAF": "DOD Architecture Framework",
    "DR": "Decommissioning Review",
    "DRM": "Design Reference Mission",
    "DRR": "Disposal Readiness Review",
    "EDL": "Entry, Descent, and Landing",
    "EEE": "Electrical, Electronic, and Electromechanical",
    "EFFBD": "Enhanced Functional Flow Block Diagram",
    "EIA": "Electronic Industries Alliance",
    "EMC": "Electromagnetic Compatibility",
    "EMI": "Electromagnetic Interference",
    "EOM": "End of Mission",
    "EVM": "Earned Value Management",
    "FA": "Formulation Agreement",
    "FAD": "Formulation Authorization Document",
    "FAR": "Federal Acquisition Regulation",
    "FCA": "Functional Configuration Audit",
    "FFBD": "Functional Flow Block Diagram",
    "FIPS": "Federal Information Processing Standard",
    "FM": "Fault Management",
    "FMEA": "Failure Modes and Effects Analysis",
    "FRR": "Flight Readiness Review",
    "FTA": "Fault Tree Analysis",
    "FTE": "Full Time Equivalent",
    "GOTS": "Government Off-The-Shelf",
    "GSE": "Government-Supplied Equipment or Ground Support Equipment",
    "GSFC": "Goddard Space Flight Center",
    "GFE": "Government Furnished Equipment",
    "GFI": "Government Furnished Information",
    "HCD": "Human-Centered Design",
    "HF": "Human Factors",
    "HITL": "Human-In-The-Loop",
    "HQ": "Headquarters",
    "HSI": "Human Systems Integration",
    "HSIP": "Human System Integration Plan",
    "HWIL": "HardWare-In-the-Loop",
    "I&T": "Integration and Test",
    "ICD": "Interface Control Document",
    "ICP": "Interface Control Plan",
    "IDD": "Interface Definition Document",
    "IDEF0": "Integration Definition for functional modeling",
    "IEEE": "Institute of Electrical and Electronics Engineers",
    "ILS": "Integrated Logistics Support",
    "INCOSE": "International Council on Systems Engineering",
    "IPT": "Integrated Product Team",
    "IRD": "Interface Requirements Document",
    "ISO": "International Organization for Standardization",
    "IT": "Information Technology",
    "ITA": "Internal Task Agreement",
    "ITAR": "International Traffic in Arms Regulation",
    "IV&V": "Independent Verification and Validation",
    "IVHM": "Integrated Vehicle Health Management",
    "IWG": "Interface Working Group",
    "JCL": "Joint cost and schedule Confidence Level",
    "JPL": "Jet Propulsion Laboratory",
    "KBSI": "Knowledge Based Systems Inc",
    "KDP": "Key Decision Point",
    "KDP-A": "Key Decision Point A",
    "KDP-B": "Key Decision Point B",
    "KDP-C": "Key Decision Point C",
    "KDP-D": "Key Decision Point D",
    "KDP-E": "Key Decision Point E",
    "KDP-F": "Key Decision Point F",
    "KDR": "Key Driving Requirement",
    "KPP": "Key Performance Parameter",
    "KSC": "Kennedy Space Center",
    "LCC": "Life Cycle Cost",
    "LEO": "Low Earth Orbit",
    "M&S": "Modeling and Simulation",
    "MBSE": "Model-Based Systems Engineering",
    "MCR": "Mission Concept Review",
    "MDAA": "Mission Directorate Associate Administrator",
    "MDR": "Mission Definition Review",
    "MEL": "Master Equipment List",
    "MODAF": "Ministry of Defense Architecture Framework",
    "MOE": "Measure of Effectiveness",
    "MOP": "Measure of Performance",
    "MOTS": "Modified Off-The-Shelf",
    "MOU": "Memorandum of Understanding",
    "MRB": "Material Review Board",
    "MRR": "Mission Readiness Review",
    "MSFC": "Marshall Space Flight Center",
    "NEN": "NASA Engineering Network",
    "NEPA": "National Environmental Policy Act",
    "NFS": "NASA FAR Supplement",
    "NGO": "Needs Goals and Objectives",
    "NIAT": "NASA Integrated Action Team",
    "NID": "NASA Interim Directive",
    "NOA": "New Obligation Authority",
    "NOAA": "National Oceanic and Atmospheric Administration",
    "NODIS": "NASA Online Directives Information System",
    "NPD": "NASA Policy Directive",
    "NPR": "NASA Procedural Requirements",
    "NRC": "Nuclear Regulatory Commission",
    "NSTS": "National Space Transportation System",
    "OCE": "Office of the Chief Engineer",
    "OCIO": "Office of the Chief Information Officer",
    "OCL": "Object Constraint Language",
    "OMB": "Office of Management and Budget",
    "ORR": "Operational Readiness Review",
    "OTS": "Off-the-Shelf",
    "OWL": "Web Ontology Language",
    "PBS": "Product Breakdown Structure",
    "PCA": "Physical Configuration Audit or Program Commitment Agreement",
    "PDR": "Preliminary Design Review",
    "PFAR": "Post-Flight Assessment Review",
    "PI": "Performance Index or Principal Investigator",
    "PIR": "Program Implementation Review",
    "PKI": "Public Key Infrastructure",
    "PLAR": "Post-Launch Assessment Review",
    "PM": "Program Manager or Project Manager",
    "PMC": "Program Management Council",
    "PPD": "Presidential Policy Directive",
    "PRA": "Probabilistic Risk Assessment",
    "PRD": "Project Requirements Document",
    "PRR": "Production Readiness Review",
    "QA": "Quality Assurance",
    "QMS": "Quality Management System",
    "QVT": "Query View Transformations",
    "R&M": "Reliability and Maintainability",
    "R&T": "Research and Technology",
    "RACI": "Responsible Accountable Consulted Informed",
    "RAM": "Reliability Availability and Maintainability",
    "REC": "Record of Environmental Consideration",
    "RFA": "Requests for Action",
    "RFP": "Request for Proposal",
    "RID": "Review Item Discrepancy or Review Item Disposition",
    "RIDM": "Risk-Informed Decision Making",
    "RM": "Risk Management",
    "RMA": "Rapid Mission Architecture",
    "RUL": "Remaining Useful Life",
    "SAR": "System Acceptance Review",
    "SBU": "Sensitive But Unclassified",
    "SDR": "Program/System Definition Review",
    "SE": "Systems Engineering",
    "SECoP": "Systems Engineering Community of Practice",
    "SEMP": "Systems Engineering Management Plan",
    "SI": "International System of Units",
    "SIR": "System Integration Review",
    "SMA": "Safety and Mission Assurance",
    "SME": "Subject Matter Expert",
    "SOW": "Statement of Work",
    "SP": "Special Publication",
    "SRD": "System Requirements Document",
    "SRR": "System Requirements Review",
    "SRS": "Software Requirements Specification",
    "STI": "Scientific and Technical Information",
    "STS": "Space Transportation System",
    "SysML": "System Modeling Language",
    "T&E": "Test and Evaluation",
    "TA": "Technical Authority",
    "TBD": "To Be Determined",
    "TBR": "To Be Resolved",
    "TEMP": "Test and Evaluation Master Plan",
    "ToR": "Terms of Reference",
    "TPM": "Technical Performance Measure",
    "TRA": "Technology Readiness Assessment",
    "TRL": "Technology Readiness Level",
    "TRR": "Test Readiness Review",
    "TVC": "Thrust Vector Controller",
    "UFE": "Unallocated Future Expenses",
    "UML": "Unified Modeling Language",
    "V&V": "Verification and Validation",
    "WBS": "Work Breakdown Structure",
    "WYE": "Work Year Equivalent",
    "XMI": "XML Metadata Interchange",
    "XML": "Extensible Markup Language",
    "ISS": "International Space Station",
    "ATP": "Authority to Proceed",
    "GEO": "Geostationary",
}
